# Generated by Django 5.0.7 on 2024-08-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='patient',
        #     name='profile_picture',
        #     field=models.ImageField(blank=True, null=True, upload_to='patient_pictures/'),
        # ),
        # migrations.AddField(
        #     model_name='profile',
        #     name='profile_picture',
        #     field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        # ),
    ]
