# Generated by Django 5.0.7 on 2024-08-03 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patient_profile_picture_profile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='appointment',
        #     name='created_by',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL),
        # ),
        migrations.AlterField(
            model_name='appointment',
            name='reason_category',
            field=models.CharField(blank=True, choices=[('Pediatrics', 'Pediatrics'), ('Antenatal Care', 'Antenatal Care'), ('Gynecology', 'Gynecology'), ('Cardiology', 'Cardiology'), ('Gastroenterology', 'Gastroenterology')], max_length=100, null=True),
        ),
    ]
