# Generated by Django 5.0.7 on 2024-08-29 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_invoice_created_at_alter_invoice_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='description',
            new_name='descriptions',
        ),
    ]
