# Generated by Django 5.0.7 on 2024-08-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_doctornote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('LabTech', 'Lab Technician'), ('Pharmacist', 'Pharmacist'), ('Receptionist', 'Receptionist'), ('Cashier', 'Cashier')], max_length=20),
        ),
    ]
