# Generated by Django 5.0.7 on 2024-08-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
