# Generated by Django 5.0.7 on 2024-08-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_prescription_is_invoiced'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='payment',
        #     old_name='billing',
        #     new_name='invoice',
        # ),
    ]
