# Generated by Django 5.0.7 on 2024-08-08 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_payment_invoice'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='billingservice',
        #     name='billing',
        # ),
        # migrations.RemoveField(
        #     model_name='billingservice',
        #     name='service',
        # ),
        migrations.AddField(
            model_name='invoiceitem',
            name='investigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.investigation'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medication'),
        ),
        # migrations.DeleteModel(
        #     name='Billing',
        # ),
        # migrations.DeleteModel(
        #     name='BillingService',
        # ),
    ]
