# Generated by Django 5.0.7 on 2024-08-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_investigationresult_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigationresult',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='investigationrequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
