# Generated by Django 5.0.7 on 2024-08-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_investigationresult_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigationrequest',
            name='is_paid',
        ),
    ]
