# Generated by Django 5.0.7 on 2024-08-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_investigationresult_age_investigationresult_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigationresult',
            name='age',
        ),
        migrations.RemoveField(
            model_name='investigationresult',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='investigationresult',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='investigationrequest',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investigationrequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investigationrequest',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
