# Generated by Django 5.0.7 on 2024-08-12 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_investigationresult_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.patient'),
        ),
    ]
