# Generated by Django 5.0.7 on 2024-08-12 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_invoice_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
        # migrations.AlterField(
        #     model_name='service',
        #     name='service_type',
        #     field=models.CharField(choices=[('General Consultation', 'General Consultation'), ('Pediatrics', 'Pediatrics'), ('Antenatal Care', 'Antenatal Care'), ('Gynecology', 'Gynecology'), ('Cardiology', 'Cardiology'), ('Gastroenterology', 'Gastroenterology'), ('NewPatient', 'New Patient'), ('Admission', 'Admission'), ('Others', 'Others')], max_length=50),
        # ),
    ]
