# Generated by Django 5.0.7 on 2024-08-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_observationchart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationchart',
            name='patient',
        ),
    ]
