# Generated by Django 5.0.7 on 2024-08-16 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_observationchart_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsign',
            name='oxygen_saturation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='pulse',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='respiratory_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DownScoreChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respiratory_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('cyanosis', models.CharField(blank=True, max_length=20, null=True)),
                ('retraction', models.CharField(blank=True, max_length=20, null=True)),
                ('grunting', models.CharField(blank=True, max_length=20, null=True)),
                ('air_entry', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.admission')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='FluidChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_type', models.CharField(blank=True, max_length=20, null=True)),
                ('intake_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('intake_route', models.CharField(blank=True, max_length=20, null=True)),
                ('output_type', models.CharField(blank=True, max_length=20, null=True)),
                ('output_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('output_remark', models.CharField(blank=True, max_length=20, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.admission')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SeizureChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.admission')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
            ],
        ),
    ]
