# Generated by Django 5.0.7 on 2024-08-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_doctornote_admission_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Dispensed', 'Dispensed')], default='Pending', max_length=50),
        ),
    ]
