# Generated by Django 5.0.7 on 2024-08-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason_category',
            field=models.CharField(blank=True, choices=[('General Consultation', 'General Consultation'), ('Pediatrics', 'Pediatrics'), ('Antenatal Care', 'Antenatal Care'), ('Gynecology', 'Gynecology'), ('Cardiology', 'Cardiology'), ('Gastroenterology', 'Gastroenterology')], max_length=100, null=True),
        ),
    ]
