# Generated by Django 5.0.7 on 2024-08-23 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_admission_ward_alter_appointment_reason_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile'),
        ),
    ]
