# Generated by Django 5.0.7 on 2024-08-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_refund_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsign',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='oxygen_saturation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='temperature',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
