# Generated by Django 5.0.7 on 2024-08-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_family_remove_patient_date_of_birth_patient_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason_category',
            field=models.CharField(blank=True, choices=[('General Consultation', 'General Consultation'), ('Pediatrics', 'Pediatrics'), ('Antenatal Care', 'Antenatal Care'), ('GynecologyRegistration', 'Gynecology Registration'), ('GynecologyFollowUp', 'Gynecology Follow Up'), ('Cardiology', 'Cardiology'), ('Gastroenterology', 'Gastroenterology')], max_length=100, null=True),
        ),
        # migrations.AlterField(
        #     model_name='service',
        #     name='service_type',
        #     field=models.CharField(choices=[('General Consultation', 'General Consultation'), ('Pediatrics', 'Pediatrics'), ('Antenatal Care', 'Antenatal Care'), ('GynecologyRegistration', 'Gynecology Registration'), ('GynecologyFollowUp', 'Gynecology Follow Up'), ('Cardiology', 'Cardiology'), ('Gastroenterology', 'Gastroenterology'), ('NewPatient', 'New Patient'), ('Admission', 'Admission'), ('Others', 'Others')], max_length=50),
        # ),
    ]
