# Generated by Django 5.0.7 on 2024-08-25 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_appointment_reason_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='investigation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.investigationrequest'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.prescription'),
        ),
    ]
