# Generated by Django 5.0.7 on 2024-08-26 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_family_created_at_family_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='family',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='family',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
