# Generated by Django 5.0.7 on 2024-08-26 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_family_created_at_family_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornote',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.appointment'),
        ),
    ]
