# Generated by Django 5.0.7 on 2024-08-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_invoiceitem_investigation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
