# Generated by Django 5.0.7 on 2024-08-28 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_invoice_custom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='investigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.investigation'),
        ),
    ]
