# Generated by Django 5.0.7 on 2024-08-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_invoiceitem_investigation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='investigation',
        ),
    ]
