# Generated by Django 5.0.7 on 2024-08-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_invoice_created_by'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='service',
        #     name='service_type',
        # ),
    ]
