# Generated by Django 5.0.7 on 2024-08-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_service_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='reason_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
