# Generated by Django 5.0.7 on 2024-08-28 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_appointment_reason_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason_category',
            field=models.CharField(blank=True, choices=[('General Consultation', 'General Consultation'), ('Pediatrics', 'Pediatrics'), ('Antenatal Care', 'Antenatal Care'), ('Gynecology Registration', 'Gynecology Registration'), ('Gynecology FollowUp', 'Gynecology Follow Up'), ('Cardiology', 'Cardiology'), ('Gastroenterology', 'Gastroenterology')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
