# Generated by Django 5.0.7 on 2024-08-28 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_admission_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='created_by',
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.doctor'),
        ),
    ]
