# Generated by Django 5.0.7 on 2024-09-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_billingservice_billing_remove_payment_billing_and_more'),
        ('core', '0002_remove_payment_billing_remove_billingservice_billing_and_more'),
        ('core', '0005_rename_description_invoiceitem_descriptions'),
        ('core', '0030_patient_age'),
        ('core', '0047_remove_admission_created_by_prescription_doctor'),
    ]

    operations = [
    ]
