# Generated by Django 5.0.7 on 2024-09-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_rename_description_invoiceitem_descriptions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='description',
            new_name='descriptions',
        ),
    ]
