# Generated by Django 5.0.7 on 2024-09-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_rename_description_invoiceitem_descriptions'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='pharmacystock',
        #     name='expiry_date',
        #     field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='pharmacystock',
        #     name='unit',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),
    ]
