# Generated by Django 5.0.7 on 2024-09-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
