# Generated by Django 5.0.7 on 2024-09-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_inventorycategory_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacystock',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacystock',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
