# Generated by Django 5.0.7 on 2024-09-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_pharmacystock_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diagnosticreporttype')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diagnostic_reports/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.diagnosticreport')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticReportParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diagnosticreporttype')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticReportResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('diagnostic_report_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diagnosticreportparameter')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diagnosticreport')),
            ],
            options={
                'unique_together': {('report', 'diagnostic_report_parameter')},
            },
        ),
    ]
