# Generated by Django 5.0.7 on 2024-09-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_diagnosticreporttype_diagnosticreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticreport',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
