# Generated by Django 5.1.2 on 2024-10-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_diagnosticreport_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacystock',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
    ]
