# Generated by Django 5.1.2 on 2024-10-27 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_pharmacystock_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacystock',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_stock_created', to='core.profile'),
        ),
        migrations.AddField(
            model_name='pharmacystock',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_stock_updated', to='core.profile'),
        ),
        migrations.CreateModel(
            name='PharmacyStockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, choices=[('Addition', 'Addition'), ('Removal', 'Removal')], max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_stock_transaction_created', to='core.profile')),
                ('pharmacy_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pharmacystock')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_stock_transaction_updated', to='core.profile')),
            ],
        ),
    ]
