# Generated by Django 5.0.7 on 2026-06-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_finalize_invoice_payment_number_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('LabTech', 'Lab Technician'), ('Pharmacist', 'Pharmacist'), ('Receptionist', 'Receptionist'), ('Cashier', 'Cashier'), ('Accountant', 'Accountant')], max_length=20),
        ),
    ]
