# Generated by Django 5.0.7 on 2026-06-23 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HMO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='file_type',
            field=models.CharField(blank=True, choices=[('Private/Individual', 'Private/Individual'), ('NHI', 'NHI'), ('Company', 'Company'), ('Family', 'Family'), ('NHI - Private', 'NHI - Private')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hmo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hmo'),
        ),
    ]
