# Generated by Django 5.0.7 on 2026-06-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_company_hmo_patient_file_type_patient_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Administrator'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('LabTech', 'Lab Technician'), ('Pharmacist', 'Pharmacist'), ('PharmacyHead', 'Pharmacy Head'), ('Receptionist', 'Receptionist'), ('Cashier', 'Cashier'), ('Accountant', 'Accountant')], max_length=20),
        ),
    ]
